Add return type to `getKlines`
tiagosiebler/binance pull request #265
Opened 2022-11-24 20:49 UTC by mkosir

## Summary
PR adds (reuses from futures) `Kline` type to spot `getKlines` function.

2022-11-24 23:05 UTC, tiagosiebler requested changes
This is great thank you. Tiny nitpick around renaming an existing exported type but otherwise great.

2022-11-24 23:05 UTC, tiagosiebler commented on src/types/shared.ts
> +
```suggestion
export type Kline = [
  number, // open time
  numberInString, // open
  numberInString, // high
  numberInString, // low
  numberInString, // close
  numberInString, // volume
  number, // close time
  numberInString, // quote asset volume
  number, // number of trades
  numberInString, // taker buy base asset vol
  numberInString, // taker buy quote asset vol
  numberInString // ignore?
];

/** @deprecated `FuturesKline` will be removed soon. Use `Kline` instead. **/
export type FuturesKline = Kline;
```

This is great, thank you! Tiny nitpick, could you add a backwards compatible type like this preserving the old name?

By removing the old one you may be causing a breaking change, and I'd rather avoid those for minor patch releases.

2022-11-24 23:08 UTC, tiagosiebler approved these changes
Actually, that was an easy commit via the suggested change. No action needed, will merge shortly. Thanks!

2022-11-24 23:09 UTC, merged

2022-11-25 08:15 UTC, mkosir commented
> This is great thank you. Tiny nitpick around renaming an existing exported type but otherwise great.

Thank you for quick resolve in merge on this PR 🚀